// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"


/** Commented Tags created in the editor */

//UE_DECLARE_GAMEPLAY_TAG_EXTERN(ACTION_ATTACKING);
//UE_DECLARE_GAMEPLAY_TAG_EXTERN(ACTION_SPRINTING);

//UE_DECLARE_GAMEPLAY_TAG_EXTERN(KEYCARD_BLUE);
//UE_DECLARE_GAMEPLAY_TAG_EXTERN(KEYCARD_GREEN);
//UE_DECLARE_GAMEPLAY_TAG_EXTERN(KEYCARD_RED);

//UE_DECLARE_GAMEPLAY_TAG_EXTERN(STATUS_PARRYING);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(STATUS_BURNING);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(STATUS_THORNS);




class ACTIONROGUELIKE_API SGameplayTags
{
};
